FROM golang:alpine3.19 as build
RUN apk add --no-cache git

WORKDIR /src 

COPY go.sum /src/
COPY go.mod /src/
RUN go mod download

COPY main.go /src
COPY log.go /src
COPY config.go /src
COPY http.go /src
COPY jaeger.go /src
COPY vault.go /src

RUN go build -o app

FROM alpine:3.19

RUN mkdir -p /app
COPY --from=build /src/app /app/app
CMD ["./app/app"]