apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlists-db
  # namespace: tracing
  labels:
    app: playlists-db
spec:
  selector:
    matchLabels:
      app: playlists-db
  replicas: 1
  template:
    metadata:
      labels:
        app: playlists-db
    spec:
      containers:
        - name: playlists-db
          image: mongo:6.0.12
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: test
          volumeMounts:
            - name: configmap
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: configmap
          configMap:
            name: playlists-db
---
apiVersion: v1
kind: Service
metadata:
  name: playlists-db
  # namespace: tracing
  labels:
    app: playlists-db
spec:
  type: ClusterIP
  selector:
    app: playlists-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
