apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-db
  namespace: tracing
  labels:
    app: videos-db
spec:
  selector:
    matchLabels:
      app: videos-db
  replicas: 1
  template:
    metadata:
      labels:
        app: videos-db
    spec:
      containers:
        - name: videos-db
          image: mongo:6.0.12
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: test
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: configmap
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: configmap
          configMap:
            name: videos-db
---
apiVersion: v1
kind: Service
metadata:
  name: videos-db
  namespace: tracing
  labels:
    app: videos-db
spec:
  type: ClusterIP
  selector:
    app: videos-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
